"""
CNA v6 — Default Card Deck (30 cards)

5개 임상축 × 6장 = 30장 기본 카드.
각 카드는 Fischer 인지축 + 임상축 타겟 + 근거 자료를 가짐.

⭐ Trade Secret 시작 자료. 할비 임상 큐레이션 자리.
새 카드 추가는 별도 YAML 또는 DB 통해.

Boston Neuromind LLC · 2026
"""

from cna_core.types import Card


def get_default_card_deck() -> list[Card]:
    """기본 30장 카드 덱. 5축 × 6장."""
    return [
        # ============================================================
        # AXIS 1: Attention (주의력) - 6장
        # ============================================================
        Card(
            id="att-001",
            target_symptoms={"inattention": 0.7, "distractibility": 0.5},
            expected_biomarker_profile={"cpt_omissions_zscore": -0.5},
            target_fischer_levels={"sustained_attention": 8.5},
            target_clinical_axes=["attention"],
            evidence_d=0.5,
            text_ko="15분 집중 자료: 하나의 과제만, 알림 다 끄고. 끝나면 5분 휴식.",
            text_en="15-min focus: one task only, all notifications off. 5-min break after.",
            cost_minutes=20,
            expected_outcome=0.55,
            information_gain_class="standard",
            instruction_steps=[
                "방해 자극 모두 제거 (핸드폰, 알림)",
                "타이머 15분 설정",
                "오직 한 과제만 수행",
                "끝나면 결과 자료 기록",
            ],
        ),
        Card(
            id="att-002",
            target_symptoms={"inattention": 0.5, "executive_dysfunction": 0.4},
            expected_biomarker_profile={"cpt_omissions_zscore": -0.3, "hrv_rmssd": 28.0},
            target_fischer_levels={"sustained_attention": 9.0},
            target_clinical_axes=["attention", "peak_performance"],
            evidence_d=0.6,
            text_ko="Pomodoro 한 사이클: 25분 집중 + 5분 휴식. 한 과제만.",
            text_en="One Pomodoro: 25 min focus + 5 min rest. One task only.",
            cost_minutes=30,
            expected_outcome=0.65,
            information_gain_class="standard",
        ),
        Card(
            id="att-003",
            target_symptoms={"inattention": 0.4},
            expected_biomarker_profile={},
            target_fischer_levels={"sustained_attention": 8.0},
            target_clinical_axes=["attention"],
            evidence_d=0.4,
            safe_for_crisis=True,
            text_ko="5분 자료 읽기: 좋아하는 책 5분만. 다른 거 하고 싶어져도 5분 유지.",
            text_en="5-min reading: favorite book for 5 min only. Stay even if you want to switch.",
            cost_minutes=5,
            expected_outcome=0.45,
            information_gain_class="low",
        ),
        Card(
            id="att-004",
            target_symptoms={"distractibility": 0.7, "executive_dysfunction": 0.5},
            expected_biomarker_profile={"cpt_rt_variability": -0.5},
            target_fischer_levels={"sustained_attention": 9.5, "self_awareness": 9.0},
            target_clinical_axes=["attention", "peak_performance"],
            evidence_d=0.55,
            text_ko="Single-tasking 자료: 1시간 동안 한 가지만. 다른 일 생각 나면 종이에 적고 다시 집중.",
            text_en="Single-tasking: 1 hour, one thing only. Write down distractions, return.",
            cost_minutes=60,
            expected_outcome=0.6,
            information_gain_class="high",
        ),
        Card(
            id="att-005",
            target_symptoms={"inattention": 0.6, "low_mood": 0.3},
            expected_biomarker_profile={"hrv_rmssd": 30.0},
            target_fischer_levels={"sustained_attention": 8.5, "emotional_regulation": 8.5},
            target_clinical_axes=["attention", "anxiety"],
            evidence_d=0.7,
            text_ko="호흡 자료 + 집중 자료: 4-7-8 호흡 3회 후 10분 집중 과제.",
            text_en="Breath + focus: 4-7-8 breathing × 3, then 10-min focus task.",
            cost_minutes=15,
            expected_outcome=0.6,
            information_gain_class="high",
            instruction_steps=[
                "4초 들숨, 7초 멈춤, 8초 날숨",
                "3회 반복",
                "이어서 10분 집중 과제",
            ],
        ),
        Card(
            id="att-006",
            target_symptoms={"executive_dysfunction": 0.6, "inattention": 0.5},
            expected_biomarker_profile={},
            target_fischer_levels={"sustained_attention": 10.0, "working_memory": 9.5},
            target_clinical_axes=["attention", "peak_performance"],
            evidence_d=0.65,
            text_ko="Implementation Intention 자료: '내가 X 상황이면 Y 한다'를 3개 미리 작성.",
            text_en="Implementation Intention: write 3 'When X, I do Y' rules in advance.",
            cost_minutes=20,
            expected_outcome=0.55,
            information_gain_class="high",
        ),
        
        # ============================================================
        # AXIS 2: Learning (학습 효율) - 6장
        # ============================================================
        Card(
            id="lrn-001",
            target_symptoms={"executive_dysfunction": 0.4},
            expected_biomarker_profile={"nback_accuracy": 0.75},
            target_fischer_levels={"working_memory": 9.0, "sustained_attention": 8.5},
            target_clinical_axes=["learning"],
            evidence_d=0.6,
            text_ko="Spaced repetition 자료: 새 자료 30분 학습, 24시간 후 5분 복습.",
            text_en="Spaced repetition: 30-min learn, 5-min review 24h later.",
            cost_minutes=35,
            expected_outcome=0.7,
            information_gain_class="standard",
        ),
        Card(
            id="lrn-002",
            target_symptoms={"executive_dysfunction": 0.5},
            expected_biomarker_profile={"nback_accuracy": 0.70, "cpt_omissions_zscore": -0.5},
            target_fischer_levels={"working_memory": 9.5, "self_awareness": 9.0},
            target_clinical_axes=["learning", "peak_performance"],
            evidence_d=0.65,
            text_ko="Active recall 자료: 자료 읽기 → 책 덮기 → 핵심 다시 쓰기. 비교.",
            text_en="Active recall: read → close → rewrite key points. Compare.",
            cost_minutes=30,
            expected_outcome=0.7,
            information_gain_class="high",
        ),
        Card(
            id="lrn-003",
            target_symptoms={"low_motivation": 0.4},
            expected_biomarker_profile={},
            target_fischer_levels={"working_memory": 8.5, "self_awareness": 9.5},
            target_clinical_axes=["learning", "depression"],
            evidence_d=0.5,
            safe_for_crisis=True,
            text_ko="Curiosity-driven 자료: 오늘 궁금한 것 1개 → 10분 자료 검색 → 핵심 3줄 정리.",
            text_en="Curiosity-driven: 1 question today → 10-min research → 3-line summary.",
            cost_minutes=15,
            expected_outcome=0.55,
            information_gain_class="high",
        ),
        Card(
            id="lrn-004",
            target_symptoms={"executive_dysfunction": 0.6},
            expected_biomarker_profile={"nback_accuracy": 0.80},
            target_fischer_levels={"working_memory": 10.0, "time_awareness": 9.5},
            target_clinical_axes=["learning", "peak_performance"],
            evidence_d=0.7,
            text_ko="Elaboration 자료: 새 개념을 자기 말로 5문장 설명 후, 기존 자료와 연결.",
            text_en="Elaboration: explain new concept in 5 sentences, connect to prior knowledge.",
            cost_minutes=25,
            expected_outcome=0.7,
            information_gain_class="high",
        ),
        Card(
            id="lrn-005",
            target_symptoms={"executive_dysfunction": 0.5, "anxiety_somatic": 0.3},
            expected_biomarker_profile={"hrv_rmssd": 28.0},
            target_fischer_levels={"working_memory": 9.0, "emotional_regulation": 9.0},
            target_clinical_axes=["learning", "anxiety"],
            evidence_d=0.55,
            text_ko="Pre-test 자료: 공부 전 5문제 풀기 (틀려도 OK) → 공부 → 다시 같은 5문제.",
            text_en="Pre-test: solve 5 problems before studying (OK to fail) → study → re-test.",
            cost_minutes=30,
            expected_outcome=0.6,
            information_gain_class="high",
        ),
        Card(
            id="lrn-006",
            target_symptoms={"executive_dysfunction": 0.7},
            expected_biomarker_profile={},
            target_fischer_levels={"working_memory": 11.0, "self_awareness": 10.0},
            target_clinical_axes=["learning", "peak_performance"],
            evidence_d=0.6,
            text_ko="Feynman 자료: 12세 아이에게 설명한다 가정하고 자료를 단순화해 작성.",
            text_en="Feynman: write as if explaining to a 12-year-old. Simplify until clear.",
            cost_minutes=25,
            expected_outcome=0.65,
            information_gain_class="high",
        ),
        
        # ============================================================
        # AXIS 3: Peak Performance (수행 최적화) - 6장
        # ============================================================
        Card(
            id="pp-001",
            target_symptoms={"executive_dysfunction": 0.6},
            expected_biomarker_profile={"time_estimation_error_pct": 15.0},
            target_fischer_levels={"time_awareness": 9.5, "sustained_attention": 9.0},
            target_clinical_axes=["peak_performance"],
            evidence_d=0.6,
            text_ko="Time Blocking 자료: 내일 일정 시간 블록으로 미리 배치 (90분 단위).",
            text_en="Time Blocking: pre-assign tomorrow's schedule in 90-min blocks.",
            cost_minutes=20,
            expected_outcome=0.65,
            information_gain_class="standard",
        ),
        Card(
            id="pp-002",
            target_symptoms={"executive_dysfunction": 0.5},
            expected_biomarker_profile={"hrv_rmssd": 30.0},
            target_fischer_levels={"emotional_regulation": 9.5, "time_awareness": 9.0},
            target_clinical_axes=["peak_performance", "anxiety"],
            evidence_d=0.65,
            text_ko="Pre-performance Routine 자료: 중요 과제 전 5분 표준 루틴 (호흡 + 시각화 + 의도).",
            text_en="Pre-performance routine: 5 min before key task (breath + visualize + intent).",
            cost_minutes=10,
            expected_outcome=0.7,
            information_gain_class="high",
        ),
        Card(
            id="pp-003",
            target_symptoms={},
            expected_biomarker_profile={"nback_accuracy": 0.75},
            target_fischer_levels={"working_memory": 10.0, "time_awareness": 9.5},
            target_clinical_axes=["peak_performance", "learning"],
            evidence_d=0.55,
            text_ko="Deliberate Practice 자료: 약한 한 부분만 집중 (1시간), 즉시 피드백.",
            text_en="Deliberate Practice: 1 hour on one weak point only, immediate feedback.",
            cost_minutes=60,
            expected_outcome=0.65,
            information_gain_class="high",
        ),
        Card(
            id="pp-004",
            target_symptoms={"low_motivation": 0.3},
            expected_biomarker_profile={},
            target_fischer_levels={"self_awareness": 10.0, "time_awareness": 9.5},
            target_clinical_axes=["peak_performance"],
            evidence_d=0.5,
            text_ko="Daily Review 자료: 매일 저녁 5분 - 잘된 것 1개, 개선 자료 1개, 내일 핵심 1개.",
            text_en="Daily Review: 5 min each night — 1 win, 1 to improve, 1 priority for tomorrow.",
            cost_minutes=5,
            expected_outcome=0.5,
            information_gain_class="high",
        ),
        Card(
            id="pp-005",
            target_symptoms={"executive_dysfunction": 0.5},
            expected_biomarker_profile={"hrv_rmssd": 32.0, "cpt_omissions_zscore": 0.0},
            target_fischer_levels={
                "sustained_attention": 10.0,
                "emotional_regulation": 9.5,
                "working_memory": 10.0,
            },
            target_clinical_axes=["peak_performance"],
            evidence_d=0.7,
            state_requirements={"hrv_min_rmssd": 25},
            text_ko="Flow Induction 자료: 명확 목표 + 적정 난이도 + 즉각 피드백 = 30-90분.",
            text_en="Flow Induction: clear goal + right challenge + immediate feedback = 30-90 min.",
            cost_minutes=60,
            expected_outcome=0.75,
            information_gain_class="high",
        ),
        Card(
            id="pp-006",
            target_symptoms={"executive_dysfunction": 0.4},
            expected_biomarker_profile={"time_estimation_error_pct": 10.0},
            target_fischer_levels={"time_awareness": 11.0, "self_awareness": 10.5},
            target_clinical_axes=["peak_performance"],
            evidence_d=0.55,
            text_ko="Energy Mapping 자료: 일주일 시간대별 에너지 0-10 기록 → 패턴 catch → 핵심 일정 매핑.",
            text_en="Energy Mapping: log energy 0-10 by hour for a week → spot pattern → align tasks.",
            cost_minutes=15,
            expected_outcome=0.6,
            information_gain_class="high",
        ),
        
        # ============================================================
        # AXIS 4: Anxiety (불안 관리) - 6장
        # ============================================================
        Card(
            id="anx-001",
            target_symptoms={"anxiety_somatic": 0.7},
            expected_biomarker_profile={"hrv_rmssd": 35.0},
            target_fischer_levels={"emotional_regulation": 8.5},
            target_clinical_axes=["anxiety"],
            evidence_d=0.7,
            safe_for_crisis=True,
            text_ko="HRV 호흡 자료: 5초 들숨, 5초 날숨 × 5분. 정확히 6회/분.",
            text_en="HRV breathing: 5-sec in, 5-sec out × 5 min. Exactly 6 breaths/min.",
            cost_minutes=5,
            expected_outcome=0.55,
            information_gain_class="standard",
            instruction_steps=[
                "편안한 자세로 앉기",
                "5초 들숨 (코로)",
                "5초 날숨 (입으로)",
                "5분 지속",
            ],
        ),
        Card(
            id="anx-002",
            target_symptoms={"anxiety_cognitive": 0.6},
            expected_biomarker_profile={},
            target_fischer_levels={"self_awareness": 9.5, "emotional_regulation": 9.0},
            target_clinical_axes=["anxiety"],
            evidence_d=0.65,
            text_ko="Worry Time 자료: 매일 정해진 15분만 걱정. 다른 시간 걱정 떠오르면 메모 후 나중에.",
            text_en="Worry Time: 15 min/day allotted to worry. Other times — note and defer.",
            cost_minutes=15,
            expected_outcome=0.6,
            information_gain_class="high",
        ),
        Card(
            id="anx-003",
            target_symptoms={"anxiety_somatic": 0.5},
            expected_biomarker_profile={"hrv_rmssd": 30.0},
            target_fischer_levels={"emotional_regulation": 8.0},
            target_clinical_axes=["anxiety"],
            evidence_d=0.55,
            safe_for_crisis=True,
            text_ko="5-4-3-2-1 Grounding 자료: 보이는 것 5, 들리는 것 4, 만지는 것 3, 냄새 2, 맛 1.",
            text_en="5-4-3-2-1 Grounding: 5 see, 4 hear, 3 touch, 2 smell, 1 taste.",
            cost_minutes=5,
            expected_outcome=0.5,
            information_gain_class="low",
        ),
        Card(
            id="anx-004",
            target_symptoms={"anxiety_cognitive": 0.5},
            expected_biomarker_profile={},
            target_fischer_levels={"self_awareness": 10.0, "working_memory": 9.0},
            target_clinical_axes=["anxiety", "depression"],
            evidence_d=0.7,
            text_ko="Cognitive Defusion 자료: 불안 생각 → '나는 ~라는 생각을 한다' 형식으로 재구성.",
            text_en="Cognitive Defusion: anxious thought → reframe as 'I'm having the thought that...'",
            cost_minutes=10,
            expected_outcome=0.6,
            information_gain_class="high",
        ),
        Card(
            id="anx-005",
            target_symptoms={"anxiety_somatic": 0.6, "anxiety_cognitive": 0.4},
            expected_biomarker_profile={"hrv_rmssd": 32.0},
            target_fischer_levels={"emotional_regulation": 9.0, "self_awareness": 9.5},
            target_clinical_axes=["anxiety"],
            evidence_d=0.6,
            text_ko="Body Scan 자료: 발끝부터 머리까지 각 부위 10초씩 자료, 긴장 풀기.",
            text_en="Body Scan: foot to head, 10 sec per part, release tension.",
            cost_minutes=15,
            expected_outcome=0.55,
            information_gain_class="standard",
        ),
        Card(
            id="anx-006",
            target_symptoms={"anxiety_cognitive": 0.7},
            expected_biomarker_profile={},
            target_fischer_levels={"self_awareness": 10.5, "working_memory": 9.5},
            target_clinical_axes=["anxiety"],
            evidence_d=0.65,
            text_ko="Probability Estimation 자료: 걱정 사건 적어 → 실제 확률 % 추정 → 증거 자료 검토.",
            text_en="Probability Estimation: write worry → estimate actual % → check evidence.",
            cost_minutes=15,
            expected_outcome=0.6,
            information_gain_class="high",
        ),
        
        # ============================================================
        # AXIS 5: Depression (기분 안정) - 6장
        # ============================================================
        Card(
            id="dep-001",
            target_symptoms={"low_mood": 0.7, "low_motivation": 0.6},
            expected_biomarker_profile={},
            target_fischer_levels={"self_awareness": 9.0},
            target_clinical_axes=["depression"],
            evidence_d=0.8,
            safe_for_crisis=True,
            text_ko="Behavioral Activation 자료: 오늘 한 가지 작은 즐거움 활동 (15분) - 미루지 말기.",
            text_en="Behavioral Activation: one small pleasant activity today (15 min) — don't postpone.",
            cost_minutes=15,
            expected_outcome=0.6,
            information_gain_class="standard",
        ),
        Card(
            id="dep-002",
            target_symptoms={"low_mood": 0.5, "anxiety_cognitive": 0.3},
            expected_biomarker_profile={},
            target_fischer_levels={"self_awareness": 10.0},
            target_clinical_axes=["depression", "anxiety"],
            evidence_d=0.7,
            text_ko="Gratitude 자료: 매일 저녁 3가지 감사한 것 구체적으로 기록 (사람, 사건, 자료).",
            text_en="Gratitude: 3 specific things tonight (person, event, detail).",
            cost_minutes=5,
            expected_outcome=0.5,
            information_gain_class="low",
        ),
        Card(
            id="dep-003",
            target_symptoms={"low_mood": 0.6, "low_motivation": 0.4},
            expected_biomarker_profile={"hrv_rmssd": 30.0},
            target_fischer_levels={"emotional_regulation": 9.0, "self_awareness": 9.5},
            target_clinical_axes=["depression"],
            evidence_d=0.75,
            safe_for_crisis=True,
            text_ko="Movement 자료: 20분 가벼운 걷기 (가능하면 햇볕). 음악 OK, 핸드폰 자료 끄기.",
            text_en="Movement: 20-min light walk (sunlight if possible). Music OK, no phone scrolling.",
            cost_minutes=20,
            expected_outcome=0.6,
            information_gain_class="standard",
        ),
        Card(
            id="dep-004",
            target_symptoms={"low_mood": 0.5},
            expected_biomarker_profile={},
            target_fischer_levels={"self_awareness": 10.5, "working_memory": 9.5},
            target_clinical_axes=["depression"],
            evidence_d=0.7,
            text_ko="Values Clarification 자료: 가장 중요한 가치 3개 적기 → 이번 주 가치 행동 1개 자료.",
            text_en="Values: write 3 most important values → 1 value-aligned action this week.",
            cost_minutes=20,
            expected_outcome=0.55,
            information_gain_class="high",
        ),
        Card(
            id="dep-005",
            target_symptoms={"low_mood": 0.4, "anxiety_cognitive": 0.4},
            expected_biomarker_profile={},
            target_fischer_levels={"self_awareness": 10.0, "emotional_regulation": 9.5},
            target_clinical_axes=["depression", "anxiety"],
            evidence_d=0.65,
            text_ko="Self-Compassion 자료: 친구한테 하듯 자기에게 말하기. 부정 자료 → 친절한 자료.",
            text_en="Self-Compassion: speak to yourself as to a friend. Harsh → kind.",
            cost_minutes=10,
            expected_outcome=0.55,
            information_gain_class="high",
        ),
        Card(
            id="dep-006",
            target_symptoms={"low_mood": 0.6, "social_withdrawal": 0.5},
            expected_biomarker_profile={},
            target_fischer_levels={"self_awareness": 9.5},
            target_clinical_axes=["depression"],
            evidence_d=0.7,
            text_ko="Social Connection 자료: 오늘 한 사람한테 짧은 메시지 자료 (그냥 안부).",
            text_en="Social Connection: send one person a short message today (just to check in).",
            cost_minutes=5,
            expected_outcome=0.5,
            information_gain_class="standard",
        ),
    ]
